FROM node:20-alpine AS build
WORKDIR /app

ARG VITE_BACKEND_URL
ARG VITE_WS_URL

COPY package*.json ./
RUN npm ci
COPY . .

RUN VITE_BACKEND_URL=$VITE_BACKEND_URL VITE_WS_URL=$VITE_WS_URL npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist ./

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
