version: "3.9"

services:
  price-poller:
    image: timzss/price-poller:latest
    container_name: price-poller
    restart: always
    env_file:
      - ./price-poller/.env
    ports:
      - "4000:4000"

  ws-server:
    image: timzss/ws-server:latest
    container_name: ws-server
    restart: always
    ports:
      - "8080:8080"

  http-backend:
    image: timzss/http-backend:latest
    container_name: http-backend
    restart: always
    env_file:
      - ./http-backend/.env
    ports:
      - "5000:5000"

  frontend:
    image: timzss/frontend:latest
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

  email-worker:
    image: timzss/email-worker:latest
    container_name: email-worker
    restart: always
    env_file:
      - ./workers/email-worker/.env
